### ISSUE TITLE
problem of not finding 'coco.json' in datasets

### ISSUE THREAD

**Issue by ShaohonChen** [pinakinathc/fscoco#3]
Hi @pinakinathc
Thanks for your excellent work! I'm having some trouble when I using clip_sbir in projects. I hope to reproduce the experiment of clip-based sbir, and download and unzip the datasets correctly. The code pop an error when I run './src/clip_sbir/main.py', says that cannot find 'coco.json'. I checked the dataset file and found that coco.json does not exist. I downloaded the datasets from Backup Storage, and I downlaoded from Official Storage to ensure the file is correct. Is there any file in the dataset that I forgot to upload or have a script can generate it?
Regards,
shaohon chen

**Comment by pinakinathc** [comment]
Hi @defineHong 
`coco.json` is the list of words used for MS-COCO datasets (or its derivatives like SketchyCOCO).

But I don't think you would need `coco.json` for an SBIR experiment (you can comment out that part in dataloader).

Nonetheless, I am providing the `coco.json` file here: [https://drive.google.com/file/d/1uxKZLGZ1hm9ognlJLTk8V5PrXfq_LTlc/view?usp=share_link](https://drive.google.com/file/d/1uxKZLGZ1hm9ognlJLTk8V5PrXfq_LTlc/view?usp=share_link) 

Please note I have hosted `coco.json` on my personal Google Drive, so please download it before I run out of space and delete it.

**Comment by ShaohonChen** [comment]
Thank you so much for your help！
I refer to your comments and modify the code in 'dataloader' to make it able to complete the SBIR task. Thanks again for your help!
